print('Hello World!')
print('Welcome to Python.')
print('Joshika')
print('i am learning python')
print('python programming')
print('good morning')
print('welcome students')
print('python is easy')
print('my first program')
print('hello from python')
